# Generated by Django 3.0.6 on 2020-05-20 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QAData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField()),
                ('question', models.TextField()),
                ('user', models.TextField()),
                ('published_date', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Demo',
        ),
    ]
