# Generated by Django 3.0.6 on 2020-05-14 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demo',
            old_name='technology',
            new_name='dl_model',
        ),
        migrations.AlterField(
            model_name='demo',
            name='image',
            field=models.FilePathField(path='images/qna.jpg'),
        ),
    ]
