# Generated by Django 3.0.6 on 2020-05-20 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demos', '0002_auto_20200520_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='qadata',
            name='answer',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
